# Site settings
title: fsainz
email: info@fsainz.com
description: "Fernando Sainz personal blog"
baseurl: ""
url: "http://www.fsainz.com"
twitter_username:
github_username:  fsainz
codepen_username:  fsainz
tumblr_username:  fsainz
mail:  info@fsainz.com
linked_in: https://de.linkedin.com/in/fernandosainz
speakerdeck_username: fsainz

# Google Maps API Key (will be injected from environment variable or .env file)
google_maps_api_key: "{{ site.google_maps_api_key | default: '' }}"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
plugins:
  - jekyll-paginate
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md",".env","vendor"]
